### ISSUE TITLE
have problem with json objects

### ISSUE THREAD

**Issue by oaminiva** [afshinm/Json-to-HTML-Table#15]
library works with jsonarrays but It does not work for me using json objects
jsonData={"x":1,"y":2,"z":3};
var jsonHtmlTable = ConvertJsonToTable(jsonData, 'jsonTable', null, 'Download');

**Comment by foxontherock** [comment]
Use that syntax: 
var jsonHtmlTable = ConvertJsonToTable(**[**jsonData**]**, 'jsonTable', null, 'Download');
to create an array with your "jsonData" variable

**Comment by afshinm** [comment]
thanks @foxontherock and sorry @oaminiva
