### ISSUE TITLE
Nesting not working.

### ISSUE THREAD

**Issue by ehwest** [afshinm/Json-to-HTML-Table#16]
I only get the top level objects in the display results.
Nesting not working?

**Comment by afshinm** [comment]
not sure @ehwest. I did this project like 4 years ago. I'm working on a new project called Gridjs that supports all types of data conversion

**Comment by taurenshaman** [comment]
@ehwest i think here needs some code to check Json object:
var jsonObject = {"Total":"34","Version":"1.0.4","Office":"New York"};
https://github.com/taurenshaman/Json-to-HTML-Table/blob/master/json-to-table.js
